Repository ProyectoUnidad8/BackEnd, pull requests merged in 2023-02, with the labels that each got.

#8 feat: add-prisma-models-usuario-pets-diagnostic-profile
  prisma/dev.db
  prisma/dev.db-journal
  prisma/migrations/20230201201649_add_models_profile_user_pet_diagnostic/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/datasource/index.ts
Labels: feature, block

#9 feat: add component user
  prisma/dev.db
  prisma/dev.db-journal
  src/app.ts
  src/components/index.ts
  src/components/users/controller.ts
  src/components/users/index.ts
  src/index.ts
  src/router/index.ts
Labels: feature

#10 fix: get pets by user id
  src/components/index.ts
  src/components/pet/controller.ts
  src/components/pet/index.ts
  src/router/index.ts
Labels: feature, fix

#11 Feat/4 component
  prisma/dev.db
  prisma/migrations/20230202164303_modify_table_pet/migration.sql
  prisma/migrations/20230202192617_modify_2_table_pet/migration.sql
  prisma/schema.prisma
  src/components/pet/controller.ts
  src/components/pet/index.ts
Labels: feature

#13 feat/6 create-middleware-and-login
  package-lock.json
  package.json
  prisma/dev.db
  prisma/migrations/20230202225629_add_col_password_in_user_model/migration.sql
  prisma/migrations/20230202232344_add_cascade_delete_on_pets_users/migration.sql
  prisma/schema.prisma
  src/components/pet/index.ts
  src/components/users/controller.ts
  src/components/users/index.ts
  src/middleware/index.ts
Labels: feature

#14 migrate sqlitedb to supabasedb/postgres and add tables PetAdoption & Application
  prisma/dev.db
  prisma/migrations/20230201201649_add_models_profile_user_pet_diagnostic/migration.sql
  prisma/migrations/20230202164303_modify_table_pet/migration.sql
  prisma/migrations/20230202192617_modify_2_table_pet/migration.sql
  prisma/migrations/20230202225629_add_col_password_in_user_model/migration.sql
  prisma/migrations/20230202232344_add_cascade_delete_on_pets_users/migration.sql
  prisma/migrations/20230204023753_first_migrate_in_supabase/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
Labels: feature, fix

#15 Feat/pet adopt
  src/components/index.ts
  src/components/petAdopt/controller.ts
  src/components/petAdopt/index.ts
  src/router/index.ts
Labels: feature, fix

#16 change fields into tables pet/ pet adopt, and add updated/created at
  prisma/migrations/20230204190014_init_migration/migration.sql
  prisma/schema.prisma
Labels: fix

#17 edit functions that make app crashed
  src/components/petAdopt/controller.ts
  src/index.ts
Labels: fix

#19 feat/5 component diagnostic
  src/components/index.ts
  src/components/petDiagnostic/controller.ts
  src/components/petDiagnostic/index.ts
  src/router/index.ts
Labels: feature

#20 fix field status on table application
  prisma/migrations/20230205092713_first/migration.sql
  prisma/schema.prisma
Labels: fix

#21 fix/4 create models
  prisma/migrations/20230205100932_first/migration.sql
  prisma/schema.prisma
Labels: fix

#22 edit data send in login
  src/components/users/controller.ts
Labels: fix

#24 add id in login data and include pets in controller diagnostic
  src/components/petDiagnostic/controller.ts
  src/components/users/controller.ts
Labels: fix

#25 fix id data in login
  src/components/users/controller.ts
Labels: fix

#26 Fix/pet diagnostic
  prisma/schema.prisma
  src/components/petDiagnostic/controller.ts
  src/components/petDiagnostic/index.ts
Labels: fix

#27 fix pet id data in diagnostic
  src/components/petDiagnostic/controller.ts
Labels: feature

#29 Hotfix/controller/pet
  babel.config.js
  jest.config.ts
  package-lock.json
  package.json
  src/components/pet/controller.ts
  test/application.test.ts
  test/petAdoption.test.ts
Labels: fix

#31 add twilio
  package-lock.json
  package.json
  src/components/application/controller.ts
  src/services/index.ts
  src/services/twilio/index.ts
Labels: feature

#33 add test and twilio service
  .github/workflows/node.js.yml
  .gitignore
  jest.config.ts
  package-lock.json
  package.json
  src/components/application/controller.ts
  src/services/index.ts
  src/services/twilio/index.ts
  test/application.test.ts
  test/pet-diagnostic.test.ts
  test/pet.test.ts
  test/petAdoption.test.ts
  test/user.test.ts
Labels: fix
